# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2432ab1e403b7c6cd8ecadc302da3fa0487050cbce6847b5522e40f5c9979c9728c240bd908d7033b4be83d57bd791ca44afdb45581373e5cb567edc91b7fd72

test:
  secret_key_base: ba6afb894525f570dc29d94350f0ecf8b6b6ba983b086fd16bff374756cb102506ffdbfdf8418eb1e47d07167d0ff157c66050ffccff20ba102db828fd004cdd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
